### ISSUE TITLE
Regression for more recent mysql connectors

### ISSUE THREAD

**Issue by MeFisto94** [aikar/db#19]
This is basically a regression from https://github.com/PaperMC/Paper/issues/5473
and also kinda explained/regressed in https://github.com/NiklasEi/gamebox/issues/87

Basically
`if (dataSourceClassName == null) tryDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");`
needs an additonal statement for `com.mysql.cj.jdbc.MysqlDataSource`

Relevant stacktrace:
```
java.lang.IllegalArgumentException: either dataSource or dataSourceClassName is required
        at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:771) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:69) ~[?:?]
        at co.aikar.idb.HikariPooledDatabase.<init>(HikariPooledDatabase.java:56) ~[?:?]
        at co.aikar.idb.BukkitDB.createHikariDatabase(BukkitDB.java:34) ~[?:?]
        at co.aikar.idb.BukkitDB.createHikariDatabase(BukkitDB.java:30) ~[?:?]
        at co.aikar.idb.BukkitDB.createHikariDatabase(BukkitDB.java:26) ~[?:?]
```

**Comment by RoinujNosde** [comment]
Check #18

**Comment by chickeneer** [comment]
The referenced PR should be merged and deployed.
